#!/usr/bin/env bash

# Regular Colors
#\[\033[0;30m\] # Black
#\[\033[0;31m\] # Red
#\[\033[0;32m\] # Green
#\[\033[0;33m\] # Yellow
#\[\033[0;34m\] # Blue
#\[\033[0;35m\] # Purple
#\[\033[0;36m\] # Cyan
#\[\033[0;37m\] # White
#
## Bold Colors
#\[\033[1;30m\] # Black
#\[\033[1;31m\] # Red
#\[\033[1;32m\] # Green
#\[\033[1;33m\] # Yellow
#\[\033[1;34m\] # Blue
#\[\033[1;35m\] # Purple
#\[\033[1;36m\] # Cyan
#\[\033[1;37m\] # White
#
## High Intensty
#\[\033[0;90m\] # Black
#\[\033[0;91m\] # Red
#\[\033[0;92m\] # Green
#\[\033[0;93m\] # Yellow
#\[\033[0;94m\] # Blue
#\[\033[0;95m\] # Purple
#\[\033[0;96m\] # Cyan
#\[\033[0;97m\] # White

## Background
#\[\033[40m\] # Black
#\[\033[41m\] # Red
#\[\033[42m\] # Green
#\[\033[43m\] # Yellow
#\[\033[44m\] # Blue
#\[\033[45m\] # Purple
#\[\033[46m\] # Cyan
#\[\033[47m\] # White
#
## High Intensty backgrounds
#\[\033[0;100m\] # Black
#\[\033[0;101m\] # Red
#\[\033[0;102m\] # Green
#\[\033[0;103m\] # Yellow
#\[\033[0;104m\] # Blue
#\[\033[10;95m\] # Purple
#\[\033[0;106m\] # Cyan
#\[\033[0;107m\] # White

#\[\033[0m\] # End Color

#Replace any leading leading 0; with 1; for bold colors
#Replace any leading 0; with 4; to underline

# change prompt
# Bash Prompt Escape Sequences
#   \a     an ASCII bell character (07)
#   \d     the date in "Weekday Month Date" format (e.g., "Tue May 26")
#   \e     an ASCII escape character (033)
#   \h     the hostname up to the first `.'
#   \H     the hostname
#   \j     the number of jobs currently managed by the shell
#   \l     the basename of the shell's terminal device name
#   \n     newline
#   \r     carriage return
#   \s     the  name  of  the shell, the basename of $0
#          (the portion following the final slash)
#   \t     the current time in 24-hour HH:MM:SS format
#   \T     the current time in 12-hour HH:MM:SS format
#   \@     the current time in 12-hour am/pm format
#   \u     the username of the current user
#   \v     the version of bash (e.g., 2.00)
#   \V     the release of bash,  version  +  patchlevel
#          (e.g., 2.00.0)
#   \w     the current working directory
#   \W     the  basename  of the current working direc­
#          tory
#   \!     the history number of this command
#   \#     the command number of this command
#   \$     if the effective UID is 0, a #, otherwise  a
#          $
#   \nnn   the  character  corresponding  to  the octal
#          number nnn
#   \\     a backslash
#   \[     begin a sequence of non-printing characters,
#          which could be used to embed a terminal con­
#          trol sequence into the prompt
#   \]     end a sequence of non-printing characters

exitstatus() { 
    if [[ $? == 0 ]]; then
        echo '\[\033[1;32m\]' # GREEN
    else
        echo '\[\033[1;31m\]' #RED
    fi
}
# PS1
export PS1="\[\033[0;37m\]\!\[\033[0m\] \[\033[1;36m\][\D{%Y%m%d} \t]\[\033[0m\] \[\033[1;35m\]\u\[\033[0m\]:\[\033[1;34m\]\W\[\033[0m\] \$ "
export PS2="| => "

# make vim the default editor
export EDITOR='/usr/bin/vim'

# Add color to Terminal
# from http://osxdaily.com/2012/02/21/add-color-to-the-terminal-in-mac-os-x/
export CLICOLOR=1
# Dark Terminal
export LSCOLORS=GxFxCxDxBxegedabagaced
# Light Terminal
# export LSCOLORS=ExFxBxDxCxegedabagacad

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'
