#!/usr/bin/env bash

# make vim the default editor
export EDITOR='/usr/bin/vim'

# Add color to Terminal
# from http://osxdaily.com/2012/02/21/add-color-to-the-terminal-in-mac-os-x/
export CLICOLOR=1
# Dark Terminal
export LSCOLORS=GxFxCxDxBxegedabagaced
# Light Terminal
# export LSCOLORS=ExFxBxDxCxegedabagacad

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'
