#!/usr/bin/env bash

# Regular Colors
BLACK="\[\033[0;30m\]"      # Black
RED="\[\033[0;31m\]"        # Red
GREEN="\[\033[0;32m\]"      # Green
YELLOW="\[\033[0;33m\]"     # Yellow
BLUE="\[\033[0;34m\]"       # Blue
PURPLE="\[\033[0;35m\]"     # Purple
CYAN="\[\033[0;36m\]"       # Cyan
WHITE="\[\033[0;37m\]"      # White

# Bold Colors
BBLACK="\[\033[1;30m\]"      # Black
BRED="\[\033[1;31m\]"        # Red
BGREEN="\[\033[1;32m\]"      # Green
BYELLOW="\[\033[1;33m\]"     # Yellow
BBLUE="\[\033[1;34m\]"       # Blue
BPURPLE="\[\033[1;35m\]"     # Purple
BCYAN="\[\033[1;36m\]"       # Cyan
BWHITE="\[\033[1;37m\]"      # White

# High Intensty
HI_BLACK="\[\033[0;90m\]"   # Black
HI_RED="\[\033[0;91m\]"     # Red
HI_GREEN="\[\033[0;92m\]"   # Green
HI_YELLOW="\[\033[0;93m\]"  # Yellow
HI_BLUE="\[\033[0;94m\]"    # Blue
HI_PURPLE="\[\033[0;95m\]"  # Purple
HI_CYAN="\[\033[0;96m\]"    # Cyan
HI_WHITE="\[\033[0;97m\]"   # White

## Background
#\[\033[40m\] # Black
#\[\033[41m\] # Red
#\[\033[42m\] # Green
#\[\033[43m\] # Yellow
#\[\033[44m\] # Blue
#\[\033[45m\] # Purple
#\[\033[46m\] # Cyan
#\[\033[47m\] # White
#
## High Intensty backgrounds
#\[\033[0;100m\] # Black
#\[\033[0;101m\] # Red
#\[\033[0;102m\] # Green
#\[\033[0;103m\] # Yellow
#\[\033[0;104m\] # Blue
#\[\033[10;95m\] # Purple
#\[\033[0;106m\] # Cyan
#\[\033[0;107m\] # White

RCol="\[\033[0m\]"          # End Color

#Replace any leading leading 0; with 1; for bold colors
#Replace any leading 0; with 4; to underline

# Change Prompt
export PS1="${BWHITE}\!${RCol} ${BCYAN}\D{%Y%m%d_%H%M}${RCol} ${BPURPLE}\u${RCol}:${BBLUE}\W${RCol} \$ "
export PS2="| => "

# make vim the default editor
export EDITOR='/usr/bin/vim'

# Add color to Terminal
# from http://osxdaily.com/2012/02/21/add-color-to-the-terminal-in-mac-os-x/
export CLICOLOR=1
# Dark Terminal
export LSCOLORS=GxFxCxDxBxegedabagaced
# Light Terminal
# export LSCOLORS=ExFxBxDxCxegedabagacad

# Increase Bash history size; default 500
export HISTSIZE='1000'
export HISTFILESIZE= # unlimited
# Omit duplicates and commands that begin with a space from history
export HISTCONTROL='ignoreboth'

# Prefer US English and use UTF-8.
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'
